spring:
  application:
    name: FlatBill-Manager-Backend

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  security:
    user:
      password: ""
